### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by GuiLec** [GuiLec/react-native-logical-tree-bot#3]
- [ ] Tests
- [ ] Make it possible to enter strings in paragraphs
- [x] Test a loop
- [ ] Prevent rendering ChatBot.Case outside a ChatBot and so on...
- [x] Doc super clean
- [x] Example super clear
- [x] How to extract cases ?
